name: Hello World Workflow

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Decir Hola 
        run: echo "Hello, Github Actions"
      - name: mostrar fecha
        run: date
      - name: listar archivos
        run: ls -la
